cake-contrib/Cake.Issues.Recipe

- Cake.Issues.Recipe/Content/IssuesBuildTasksDefinitions.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
- Cake.Issues.Recipe/Content/tasks/azuredevops.cake
- Cake.Issues.Recipe/Content/tasks/tasks.cake
Support to set status on an Azure Repos pull request from an Azure Pipeline build
Fixes #10
> (GH-10) Support to set status on an Azure Repos pull request from an Azure Pipeline build

- Cake.Issues.Recipe/Content/IssuesBuildTasksDefinitions.cake
- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
- Cake.Issues.Recipe/Content/tasks/azuredevops.cake
Create issues report and publish as artifact
Fixes #15
> (GH-15) Create report and publish as artifact

- Cake.Issues.Recipe/Content/AzurePipelineSummary.cshtml
- Cake.Issues.Recipe/Content/IssuesBuildTasksDefinitions.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
- Cake.Issues.Recipe/Content/tasks/azuredevops.cake
Create summary report for Azure Pipelines
Fixes #16
> (GH-16) Create summary report for Azure Pipelines

- README.md
Add link to Azure Pipelines / Azure Repos demo
> Add link to Azure DevOps demo

- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
Add support for InspectCode
Fixes #4
> (GH-4) Add support for InspectCode

- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequstSystemHelper.cake
Fix Azure DevOps access token fix
> Fix Azure DevOps access token fix

- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersBuildServer.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersPullRequestSystem.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersReporting.cake
- Cake.Issues.Recipe/Content/parameters/parameters.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServerHelper.cake
> Split parameters class

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.MsBuild to 0.6.3
Fixes #42
> (GH-42) Update Cake.Issues.MsBuild to 0.6.3

- Cake.Issues.Recipe/Content/addins.cake
Update to Cake.Issues 0.7.0
Fixes #43
> (GH-43) Update to Cake.Issues 0.7.0

- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
Add support for MsBuild binary log files 
Fixes #7
> (GH-7)  Add support for MsBuild binary log files 

- Cake.Issues.Recipe/Content/build.cake
> Add task descriptions

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Git to 0.21.0
Fixes #51
> (GH-51) Update Cake.Git to 0.21.0

- Cake.Issues.Recipe/Cake.Issues.Recipe.nuspec
- README.md
Website changed to cakeissues.net
Fixes #54
> (GH-54) Change website to cakeissues.net

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.Reporting.Generic to 0.7.1
Fixes #56
> (GH-56) Update Cake.Issues.Reporting.Generic to 0.7.1

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.PullRequests.Tfs to 0.7.2 and Cake.Tfs to 0.3.2
Fixes #58
> (GH-58) Update Cake.Issues.PullRequests.Tfs to 0.7.2

- Cake.Issues.Recipe/Content/data/IssuesData.cake
Use correct interfaces in IssuesData
Fixes #62
> (GH-62) Use correct interfaces

- Cake.Issues.Recipe/Content/build.cake
Fix check if running build for pull request
Fixes #64
> (GH-64) Fix check if running build for pull request

- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
Fix access to repository remote URL
Fixes #66
> (GH-66) Fix access to repository remote URL

- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
Fix access to pull request ID
Fixes #68
> (GH-68) Fix access to pull request ID

- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/BasePullRequestSystem.cake
Implement IIssuesPullRequestSystem in BasePullRequestSystem
Fixes #70
> (GH-70) Implement IIssuesPullRequestSystem in BasePullRequestSystem

- README.md
Fix link to Demo Azure Pipelines
> Fix link to Demo Azure Pipelines

- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/buildservers.cake
- README.md
- docs/supported-tools.md
Adds support for building on AppVeyor
Fixes #23
> (GH-23) Add support for building on AppVeyor

- README.md
Show Azure Pipelines  status in README
> Show Azure Pipelines  status in README

- Cake.Issues.Recipe/Content/IssuesBuildTasksDefinitions.cake
- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/BaseBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/IIssuesBuildServer.cake
- docs/configuration.md
- docs/supported-tools.md
- docs/tasks.md
Add capability to report issues to build server. Implemented for AppVeyor.
Fixes #86
> (GH-86) Support reporting issues to build server

- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzurePipelineSummary.cshtml
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
Updates to Cake.Issues 0.8.0
Fixes #76
> (GH-76) Update to Cake.Issues 0.8.0

- tests/integration/tests.cake
Set build indentifier in integration tests
> Set build indentifier in integration tests

- Cake.Issues.Recipe/Content/build.cake
Skip task integrating with build server or pull request system while running locally
Fixes #93
> (GH-93) Skip task integrating with build server or pull request system while running locally

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.Reporting.Generic to 0.8.1
Fixes #96
> (GH-96) Update Cake.Issues.Reporting.Generic to 0.8.1

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.AzureDevOps to 0.4.4
Fixes #100
> (GH-100) Update Cake.AzureDevOps to 0.4.4

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues to 0.8.1
Fixes #104
> (GH-104) Update Cake.Issues to 0.8.1

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.Reporting.Generic to 0.8.2
Fixes #105
> (GH-105) Update Cake.Issues.Reporting.Generic to 0.8.2

- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
- docs/supported-tools.md
Add support for reporting issues to Azure Pipelines.
Fixes #109
> (GH-109) Report issues to Azure Pipelines

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.PullRequests to 0.8.1
Fixes #111
> (GH-111) Update Cake.Issues.PullRequests to 0.8.1

- docs/supported-tools.md
Document that Azure Pipelines only shows 10 issues
Fixes #113
> (GH-113) Document that Azure Pipelines only shows 10 issues

- Cake.Issues.Recipe/Content/addins.cake
Updates Cake.Git to 0.22.0
Fixes #116
> (GH-116) Update Cake.Git to 0.22.0

- .appveyor.yml
- recipe.cake
Update build script to beta version of Cake.Recipe. This fixes the issues of sending two notifications on a release.
> Update to Cake.Recipe 1.1.2 beta 1

- recipe.cake
Update to final version of Cake.Recipe 1.1.2
> Update to Cake.Recipe 1.1.2 final

- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
- docs/configuration.md
- docs/supported-tools.md
- tests/integration/build.cake
- tests/integration/buildData.cake
- tests/integration/src/ClassLibrary1/Class1.cs
Adds support for JetBrains dupFinder issues using Cake.Issues.DupFinder by @janniksam.
> (GH-110) Add support for JetBrains dupFinder

- Cake.Issues.Recipe/Content/addins.cake
Update addins to latest beta versions
> Update addins to latest beta versions

- Cake.Issues.Recipe/Content/data/IssuesData.cake
Write log messages for detected settings
> Log detected settings

- azure-pipelines.yml
- tests/integration/buildData.cake
Publish generated reports as build artifacts
> Publish generated reports as build artifacts

- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
- tests/integration/build.cake
Support running in subfolder of repository
> Support running in subfolder of repository

- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/BaseBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/IIssuesBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/BasePullRequestSystem.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/GitHubPullRequestSystem.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/IIssuesPullRequestSystem.cake
Add file linking support for repos hosted on Azure Repos or GitHub
Fixes #20
> (GH-20) Add file linking support

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues to 0.9.1
Fixes #144
> (GH-144) Update to Cake.Issues 0.9.1

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Issues.PullRequests.AzureDevOps to 0.9.1
Fixes #146
> (GH-146) Update Cake.Issues.PullRequests.AzureDevOps to 0.9.1

- Cake.Issues.Recipe/Content/data/IssuesData.cake
Improve logging for properties detected by the build server abstraction.
Fixes #152
> (GH-152) Improve logging for build server properties

- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/GitHubActionsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/buildservers.cake
- docs/supported-tools.md
Add support for GitHub Actions
Fixes #148
> (GH-148) Add support for GitHub Actions

- Cake.Issues.Recipe/Content/tasks/buildservers/GitHubActionsBuildServer.cake
Group issues by provider and run in the build log output when running on GitHub Actions
> Group issues by provider and run when running on GitHub Actions

- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/GitHubActionsBuildServer.cake
Replace GitHub Actions support with Cake.Issues.PullRequests.GitHubActions
> (GH-154) Use Cake.Issues.PullRequests.GitHubActions

- .appveyor.yml
- build.ps1
- build.sh
- recipe.cake
- tools/packages.config
Update build script to latest alpha version of Cake.Recipe.
> Update build script to Cake.Recipe 2.0 alpha

- Cake.Issues.Recipe/Content/addins.cake
Update to Cake.Issues.MsBuild 0.9.1
Fixes #158
> (GH-158) Update to Cake.Issues.MsBuild 0.9.1

- Cake.Issues.Recipe/Content/addins.cake
Update to Cake.Issues.PullRequests 0.9.1
Fixes #160
> (GH-160) Update to Cake.Issues.PullRequests 0.9.1

- recipe.cake
> Update Cake.Recipe to 2.1.0

- tests/integration/.config/dotnet-tools.json
- tests/integration/build.ps1
- tests/integration/build.sh
- tests/integration/tools/packages.config
Update integration tests to Cake 1.0.0
> Update integration tests to Cake 1.0.0

- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/BaseBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/GitHubActionsBuildServer.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/GitHubPullRequestSystem.cake
> Use NotNull extension

- Cake.Issues.Recipe/Content/addins.cake
Update Cake.Git to 1.0.0
Fixes #165
> (GH-165) Update Cake.Git to 1.0.0

- .appveyor.yml
- .github/workflows/build.yml
- azure-pipelines.yml
Use double dash syntax for arguments of integration tests
> Use double dash syntax for arguments

- .github/dependabot.yml
Add Dependabot for Frosting recipe
> Add Dependabot for Frosting recipe

- .github/dependabot.yml
> Fix scheduling of Dependabot

- Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe.csproj
- nuspec/nuget/Cake.Issues.Recipe.nuspec
> Update NuGet package tags

- Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe/Context/Parameters/IssuesParametersInputFiles.cs
- Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe/ReadIssuesTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
- tests/frosting/net5.0/build/Program.cs
- tests/script-runner/build.cake
Support passing of read settings for the different log files. Also allows to read multiple files from the same type with different settings.
Fixes #176
> (GH-176) Support defining of read settings for log files

- Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe/Cake.Issues.FrostingRecipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
Update to Cake.Issues 1.0
Fixes #156
> (GH-156) Update to Cake.Issues 1.0

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersBuildServer.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersReporting.cs
Enable report generation for Frosting recipe
> Enable report generation for Frosting recipe

- .github/dependabot.yml
Ignore Cake.Frostring minor updates for Depandabot
> Ignore Cake.Frostring minor updates for Depandabot

- tests/frosting/net5.0/nuget.config
Use local packages folder instead of default global folder.
> Use local packages folder

- docs/overview.md
Add missing link to Frosting recipe
> Add missing link

- tests/frosting/net5.0/build/Program.cs
Enable creation of issue report in Frosting integration test
> Create issue report in Frosting test

- docs/tasks.md
Improve styling of task documentation by adding manual line breaks
> Improve styling of task documentation

- docs/supported-tools.md
Update tool documentation to 1.0
> Update tool documentation to 1.0

- tests/frosting/net5.0/build/Program.cs
Cleanup Frosting integration tests
> Cleanup Frosting integration tests

- docs/usage/using-cake-frosting-issues-recipe.md
Improve example for Cake Frosting
> Improve example for Cake Frosting

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/CreateFullIssuesReportTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/CreateSummaryIssuesReportTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PublishIssuesArtifactsTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReadIssuesTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReportIssuesToBuildServerTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReportIssuesToPullRequestTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/CliRepositoryInfoProvider.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/SetPullRequestIssuesStateTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/data/repositoryinfoprovider/CliRepositoryInfoProvider.cake
Enable .NET Analyzers and fix some issues
> Enable .NET Analyzers

- .gitignore
- Cake.Frosting.Issues.Recipe/.cr/personal/FavoritesList/List.xml
Remove personal CodeRush configuration
> Remove CodeRush configuration

- GitReleaseManager.yaml
Include dependencies in release notes
> Include dependencies in release notes

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersReporting.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/CreateFullIssuesReportTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersReporting.cake
Add possibility to override settings for full issues report
Fixes #118
> (GH-118) Add possibility to override settings for full issues report

- docs/overview.md
Add documentation for addins bundled with recipes
> Add documentation for addins bundled with recipes

- docs/configuration.md
Add documentation for `FullIssuesReportSettings` parameter
> Add documentation for FullIssuesReportSettings parameter

- azure-pipelines.yml
- tests/frosting/net5.0/build/Program.cs
Publish Frosting integration tests artifact
> Publish Frosting integration tests artifact

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReadIssuesTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- tests/frosting/net5.0/build/Program.cs
Use project root directory for reading issues.
Fixes #230
> (GH-230) Use project root directory for reading issues

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/AzureDevOpsBuildServer.cs
- Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
Use project root directory for creating summary issue report
Part of #233
> (GH-233) Use project root directory for creating summary issue report

- docs/overview.md
Update documentation for bundled markdownlint parser version
> Update documentation for bundled markdownlint parser version

- Cake.Issues.Recipe/Content/data/repositoryinfoprovider/CliRepositoryInfoProvider.cake
Fixes #247. 'Environment' does not contain a definition for 'NewLine'
> Fixes #247. 'Environment' does not contain a definition for 'NewLine'

- .appveyor.yml
> Fix AppVeyor build

- azure-pipelines.yml
Run macOS tests on macOS 11 instead of deprecated macOS 10.15
> Run macOS tests on macOS 11

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/AzurePipelineSummary.cshtml
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/tasks/buildservers/AzurePipelineSummary.cshtml
- tests/frosting/net5.0/build/Build.csproj
- tests/script-runner/.config/dotnet-tools.json
Update Addins to Cake 2.x compatible versions
Fixes #256
> Update Addins to Cake 2.x compatible versions

- .github/dependabot.yml
Ignore Cake updates for dependabot until 3.0
> Ignore Cake updates until 3.0

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.sln
Update solution to Visual Studio 2022
> Update solution to Visual Studio 2022

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/CakeGitRepositoryInfoProvider.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/CliRepositoryInfoProvider.cs
Mark IRepositoryInfoProvider implementations as internal
Fixes #220
> (GH-220) Mark IRepositoryInfoProvider implementations as internal

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/AzureDevOpsPullRequestSystem.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReportIssuesToPullRequestTask.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/SetPullRequestIssuesStateTask.cs
Remove DupFinder exclusions since we no longer run DupFinder during builds
> Remove DupFinder exclusions

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IIssuesState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/AzureDevOpsPullRequestSystem.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReadIssuesTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/data/IssuesData.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
Makes sure that we report pull request state for individual issue providers even if no issues are reported for the issue provider or run.
> Set pull request state for issue providers for which no issues are reported

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IIssuesState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
- Cake.Issues.Recipe/Content/data/IssuesData.cake
Return issues from `AddIssues` when an issue provider is passed.
> Return issues from AddIssues

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
- Cake.Issues.Recipe/Content/data/IssuesData.cake
> Use null reference helper

- recipe.cake
Remove CakeVersion from BuildMetaDataCakeIssuesRecipe.
Fixes #295
> Remove CakeVersion from BuildMetaDataCakeIssuesRecipe

- .gitignore
- recipe.cake
Add version.yml file to Cake.Issues.Recipe
Generated file `cake-version.yml` in root folder will look like this:
```
TargetCakeVersion: 2.0.0
TargetFrameworks:
- netcoreapp3.1
- net5.0
- net6.0
```
Fixes #298
> Add cake-version.yml file to Cake.Issues.Recipe

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
Update Cake.AzureDevOps to 2.0
> Update Cake.AzureDevOps to 2.0

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
Updates to Cake.Issues 2.0.0-beta0003
> Update to Cake.Issues 2.0.0-beta0003

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
Updates Cake.Issues.Markdownlint to 2.0.0 Beta 2
> Update Cake.Issues.Markdownlint to 2.0.0 Beta 2

- .github/workflows/build.yml
- azure-pipelines.yml
Ensure required .NET versions are available during build
> Ensure required .NET versions are available

- .appveyor.yml
Ensure required .NET versions are available on AppVeyor
> Ensure required .NET versions are available on AppVeyor

- .github/renovate.json
Update Frosting only to major versions
> Update Frosting only to major versions

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
- docs/overview.md
Updates all addins to Cake.Issues 4.0
Fixes #390 
Fixes #393
Fixes #396
> Update to Cake.Issues 4.0

- .appveyor.yml
- azure-pipelines.yml
Update integration tests to Node 20
> Update integration tests to Node 20

- .github/renovate.json
Group Cake.Issues addins for Frosting and Scripting in a single pull request
> Group Cake.Issues addins for Frosting and Scripting

- tests/frosting/net6.0/build/Program.cs
- tests/frosting/net7.0/build/Program.cs
- tests/frosting/net8.0/build/Program.cs
Pin InspectCode to 2023.3.4 since starting with 2024.1.0 default format is SARIF
> Pin InspectCode to 2023.3.4

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.Reporting
Fixes #408
> (GH-408) Use Cake.Frosting.Issues.Reporting

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.InspectCode
Fixes #425
> (GH-425) Use Cake.Frosting.Issues.InspectCode

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.EsLint
Fixes #427
> (GH-427) Use Cake.Frosting.Issues.EsLint

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.PullRequests.AppVeyor
Fixes #428
> (GH-428) Use Cake.Frosting.Issues.PullRequests.AppVeyor

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.PullRequests.GitHubActions
Fixes #430
> (GH-430) Use Cake.Frosting.Issues.PullRequests.GitHubActions

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- docs/overview.md
Use Cake.Frosting.Issues.PullRequests.AzureDevOps
Fixes #429
> (GH-429) Use Cake.Frosting.IssuesPullRequests.AzureDevOps

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/IssuesContext{TParameters,TState}.cs
Output version of Cake.Frosting.Issues.Recipe like we already do for Cake.Issues.Recipe
> Output version of Cake.Frosting.Issues.Recipe

- docs/overview.md
Fixes links to addin documentation for Cake Frosting addins
> Fix links to addin documentation

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.targets
- tests/frosting/net6.0/build/Build.csproj
- tests/frosting/net6.0/build/Program.cs
- tests/frosting/net7.0/build/Build.csproj
- tests/frosting/net7.0/build/Program.cs
- tests/frosting/net8.0/build/Build.csproj
- tests/frosting/net8.0/build/Program.cs
Provide implicit usings for Cake.Frosting.Issues.Recipe
> Provide implicit usings

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/BasePullRequestSystem.cs
Add log output for configuration to report issues to pull requests.
> Add log output for pull request configuration

- azure-pipelines.yml
> Update macOS images

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.Tests/Cake.Frosting.Issues.Recipe.Tests.csproj
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.Tests/FakeIssueProvider2.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.Tests/PullRequestSystems/PullRequestStatusCalculatorTests.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.lutconfig
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.sln
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Properties/ProjectInfo.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/AzureDevOpsPullRequestSystem.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/PullRequestStatus.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/PullRequestStatusCalculator.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/PullRequestStatusExtensions.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/PullRequestStatusState.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/PullRequestStatusStateExtensions.cs
- Cake.Frosting.Issues.Recipe/Cake.Issues.Tests.ruleset
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/PullRequestStatus.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/PullRequestStatusCalculator.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/PullRequestStatusExtensions.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/PullRequestStatusState.cake
- Cake.Issues.Recipe/Content/tasks/pullrequestsystems/PullRequestStatusStateExtensions.cake
Refactors the code to determine status which need to be set on pull requests and fixes issues with different provider name on issue than on provider.
Also adds a test project to test the new code.
Fixes #474
> (GH-474) Fix issues with different provider on issue than on provider

- recipe.cake
> Update GitVersion to 5.12.0

- .appveyor.yml
- Cake.Frosting.Issues.Recipe/global.json
- tests/frosting/net6.0/global.json
- tests/frosting/net7.0/global.json
- tests/frosting/net8.0/global.json
- tests/script-runner/global.json
Fix .NET SDK through global.json. Also updates AppVeyor builds to use latest .NET SDK versions.
> Add global.json

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.Tests/Cake.Frosting.Issues.Recipe.Tests.csproj
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Issues.Recipe/Content/addins.cake
- docs/overview.md
Updates Cake.Issues to 5.0.0-beta0001
> Update Cake.Issues to 5.0.0-beta0001

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParametersInputFiles.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersInputFiles.cs
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
Remove obsolete members from `IssuesParametersInputFiles`
> Remove obsolete members from IssuesParametersInputFiles

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
Switch to use Use Cake.Frosting.AzureDevOps for Cake.Frosting.Issues.Recipe
> Use Cake.Frosting.AzureDevOps

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersInputFiles.cs
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
Improve exception if same file is added twice for the same issue provider
Fixes #538
> Improve exception if same file is added twice for the same issue provider

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParameters.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParametersBuildBreaking.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParameters.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersBuildBreaking.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParameters{TInputFiles,TReporting,TBuildServer,TPullRequestSystem}.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/IssuesTask.cs
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersBuildBreaking.cake
- Cake.Issues.Recipe/Content/parameters/parameters.cake
Adds configuration to fail builds when issues were reported.
Fixes #537
> Add support for breaking builds when issues are reported

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/IssuesTask.cs
- Cake.Issues.Recipe/Content/build.cake
Writes issues leading to build failure to console before breaking build.
Fixes #544
> Print issues to console in case build is failed

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParametersInputFiles.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParametersInputFilesExtensions.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersInputFiles.cs
- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/ReadIssuesTask.cs
- Cake.Issues.Recipe/Content/addins.cake
- Cake.Issues.Recipe/Content/build.cake
- Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
Add support for Test Anything Protocol format.
Fixes #534
> Add support for TAP format

- Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/IssuesTask.cs
Add note that not all issues can be printed on build breaking
Fixes #553
> Add note that not all issues can be printed on build breaking

- .github/renovate.json
Groups pull requests for updates of Cake.AzureDevOps addins
> Group pull requests for Cake.AzureDevOps addins

- .github/workflows/build.yml
- azure-pipelines.yml
Removes tests running on Windows 2019 and adds tests running on Windows 2025
> Test on Windows 2025 instead of 2019
