cake-contrib/Cake.Issues.Recipe

Cake.Issues.Recipe/Content/build.cake
Cake.Issues.Recipe/Content/parameters/IssuesParameters.cake
Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake
Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
docs/configuration.md

Add support for defining build identifiers which are used for file name of full report and summary report, and also for name of pull request status.
Fixes #72

(GH-72) Add support for build identifiers 

---

Cake.Issues.Recipe/Content/build.cake
setup.cake

Renames BuildMetaData to BuildMetaDataCakeIssuesRecipe
Fixes #91

(GH-91) Give BuildMetaData a unique name

---

Cake.Issues.Recipe/Content/build.cake

Don't throw exception if no files are passed for analyzing
Fixes #98

(GH-98) Don't throw exception if no files are passed for analyzing

---

Cake.Issues.Recipe/Content/build.cake
Cake.Issues.Recipe/Content/parameters/IssuesParametersInputFiles.cake
docs/configuration.md
docs/supported-tools.md

Add support for files generated by markdownlint with `options.resultVersion` set to 1 as input.
Fixes #6

(GH-6) Add support for markdownlint

---

.appveyor.yml

Use node.js version 14 on AppVeyor

Use node.js version 14 on AppVeyor

---

tests/integration/build.cake

Improve build identifier in integration tests to allow more platforms and runtimes.

Improve build identifier in integration tests

---

.appveyor.yml

Since integration tests on AppVeyor have repo root as working directory it doesn't find the NuGet package created in the build step and instead tests with latest version from nuget.org. This PR fixes this by setting the working directory.

Use current NuGet package for integration tests on AppVeyor

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/BaseBuildServer.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/IssuesContext.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/RepositoryInfoProviderType.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/CakeGitRepositoryInfoProvider.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/CliRepositoryInfoProvider.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/RepositoryInfo/IRepositoryInfoProvider.cs
Cake.Issues.Recipe/Content/build.cake
Cake.Issues.Recipe/Content/data/IssuesData.cake
Cake.Issues.Recipe/Content/data/RepositoryInfoProviderType.cake
Cake.Issues.Recipe/Content/data/data.cake
Cake.Issues.Recipe/Content/data/repositoryinfoprovider/CakeGitRepositoryInfoProvider.cake
Cake.Issues.Recipe/Content/data/repositoryinfoprovider/CliRepositoryInfoProvider.cake
Cake.Issues.Recipe/Content/data/repositoryinfoprovider/IRepositoryInfoProvider.cake
Cake.Issues.Recipe/Content/data/repositoryinfoprovider/repositoryinfoprovider.cake
tests/frosting/net5.0/build/Program.cs
tests/script-runner/build.cake

Add configuration option to either use Cake.Git or Git CLI
Fixes #183

(GH-183) Add option to use Git CLI

---

docs/configuration.md

Add documentation for Git repository info provider configuration
Part of #183

(GH-183) Add documentation for Git repository info provider configuration

---

docs/usage.md
docs/usage/index.cshtml
docs/usage/using-cake-frosting-issues-recipe.md
docs/usage/using-cake-issues-recipe.md

Move examples from Cake.Issues.Website to Cake.Issues.Recipe repo.
Also updates examples to Cake.Issues recipes 1.0.
Part of https://github.com/cake-contrib/Cake.Issues.Website/issues/184

Add examples from Cake.Issues.Website

---

tests/frosting/net5.0/build.ps1
tests/frosting/net5.0/build.sh

Make sure to always use latest version of Cake.Frosting.Issues.Recipe in Frosting integration tests

Make sure to always use latest version in Frosting tests

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/CreateFullIssuesReportTask.cs
Cake.Issues.Recipe/Content/build.cake

Use project root directory instead of build directory for creating issue report.
Fixes #233

(GH-233) Use project root directory for creating issue report

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/AzureDevOpsPullRequestSystem.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/GitHubPullRequestSystem.cs
Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake
Cake.Issues.Recipe/Content/tasks/pullrequestsystems/GitHubPullRequestSystem.cake

Use project root directory for file link settings
Part of #230

(GH-230) Use project root directory for file link settings

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/AppVeyorBuildServer.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/GitHubActionsBuildServer.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/PullRequestSystems/AzureDevOpsPullRequestSystem.cs
Cake.Issues.Recipe/Content/tasks/buildservers/AppVeyorBuildServer.cake
Cake.Issues.Recipe/Content/tasks/buildservers/GitHubActionsBuildServer.cake
Cake.Issues.Recipe/Content/tasks/pullrequestsystems/AzureDevOpsPullRequestSystem.cake

Use project root directory instead of build directory for reporting issues to pull request systems.
Fixes #231

(GH-231) Use project root directory for reporting issues to pull request systems

---

azure-pipelines.yml
recipe.cake
tests/script-runner/build.cake

Updates Cake.Recipe to 2.2.1, runs Linux tests on Ubuntu 18.04 and fixes JetBrains tools version.

Update Cake.Recipe to 2.2.1

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
Cake.Issues.Recipe/Content/addins.cake

Since Cake.AzureDevOps 1.1 introduces a breaking change we need to revert back to 1.0
Reverts #246
Fixes #258

Change Cake.AzureDevOps from 1.1 to 1.0

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj

Multi-Target Frosting Recipe to .NET Core 3.1, 5, & 6 to follow best-practices for Cake 2.0.
Fixes #262

(GH-262) Multi-Target .NET Core 3.1, 5 & 6 instead of .NET Standard 2.0

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/SetPullRequestIssuesStateTask.cs

Use `ShouldSetPullRequestStatus` instead of `ShouldReportIssuesToPullRequest` to control setting of pull request state.

(GH-281) Use ShouldSetPullRequestStatus to control setting of pull request state

---

azure-pipelines.yml

Remove testing on deprecated Ubuntu 18.04 image on Azure Pipelines and test on Ubuntu 22.04 instead.

Test against Ubuntu 22.04

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/State/IssuesState.cs
Cake.Issues.Recipe/Content/data/IssuesData.cake

Fixes bug where Git CLI instead of Cake.Git is used when `RepositoryInfoProviderType.CakeGit` is configured
Fixes #289

(GH-289) Use Cake.Git when RepositoryInfoProviderType.CakeGit is configured

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IIssuesParametersReporting.cs
Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersReporting.cs
Cake.Issues.Recipe/Content/parameters/IssuesParametersReporting.cake

Makes `FullIssuesReportSettings` writable to allow creating settings object for a different template.
Fixes #301

(GH-301) Make FullIssuesReportSettings writable

---

.github/dependabot.yml

Increase allowed number of Dependabot PRs, since during a release branch number of updated addins can be more than 10

Increase allowed number of dependabot PRs

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe.csproj
Cake.Issues.Recipe/Content/addins.cake
docs/overview.md
recipe.cake
tests/frosting/net6.0/build/Build.csproj
tests/frosting/net6.0/build/Program.cs
tests/frosting/net7.0/build/Build.csproj
tests/frosting/net7.0/build/Program.cs
tests/script-runner/.config/dotnet-tools.json
tests/script-runner/build.cake
tests/script-runner/tools/packages.config

Builds against Cake 3.0.
Also updates the following addins:
- Cake.Git to 3.0
- Cake.AzureDevOps to 3.0
- Cake.Issues to 3.0 Beta
Fixes #330

Build against Cake 3.0

---

tests/script-runner/build.cake

Update InspectCode in integration tests for scripting engine to 2023.1.2

Use InspectCode 2023.1.2 in integration tests

---

README.md

Replaces link to Gitter Chat with link to GitHub Discussions in README
Fixes #164

(GH-164) Replace Gitter with GitHub Discussions in README

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/BuildServers/AzureDevOpsBuildServer.cs
Cake.Issues.Recipe/Content/tasks/buildservers/AzureDevOpsBuildServer.cake

Publish SARIF report to separate folder on Azure Pipelines, to avoid having files linked twice on the build
Fixes #374

(GH-374) Publish SARIF report to separate folder on Azure Pipelines

---

Cake.Frosting.Issues.Recipe/Cake.Frosting.Issues.Recipe/Context/Parameters/IssuesParametersPullRequestSystem.cs

Makes `ProviderIssueLimits` and `IssueFilters` a proper initialized property
Fixes #462

(GH-462) Fix setting of ProviderIssueLimits and IssueFilters
